 ###  ansible all -i inv  -e ansible_user=centos  -e ansible_password=DevOps321 -m gather_facts


- name: Demo on facts 
hosts: all
tasks:
 - name: Printing the facts
      ansible.builtin.debug:
        msg: Os distribution is {{ansible_distribution}}  