# usage of shell module is trticly restricted
    
- name: Demo on using shell commands 
  hosts: all 
  tasks: 
    - name: Running uptime command 
      ansible.builtin.shell: uptime
      register: OUT
    - name: Printing SYSTEM UPTIME
      ansible.builtin.debug:
        msg: "uptime is {{OUT.stdout_lines}}"
