
- name: Demo on tags  
  hosts: all
  tasks:
    - name: Installing frontend
      ansible.builtin.debug: 
        msg: Installing frontend
      tags: frontend                       # Tagging tasks

    - name: Starting frontend
      ansible.builtin.debug: 
        msg: Starting frontend
      tags: frontend

    - name: Installing DB
      ansible.builtin.debug: 
        msg: Installing DB
      tags: db      